version: '3.1'

services:
  wordpress:
    image: wordpress:5.6.0-php7.4
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - /home/ec2-user/efs:/var/www/html
